#!/bin/bash
#PBS -q {{q}}
#PBS -l walltime={{walltime}}
#PBS -l ncpus={{ncpus}}
#PBS -l mem={{mem}}
#PBS -l jobfs={{jobfs}}
#PBS -N {{{name}}}
#PBS -l wd

source /scratch/bt62/fv3851/GridapMHD.jl/analysis/scripts/env.sh

mpiexec -n {{n}} julia --project=$GRIDAPMHD -J $GRIDAPMHD/GridapMHD.so -O3 --check-bounds=no -e\
'
using GridapMHD: hunt
hunt(
  nc={{nc}},
  np={{np}},
  backend=:mpi,
  L=1.0,
  B={{B}},
  debug={{debug}},
  vtk={{vtk}},
  title="{{{title}}}",
  path="{{{path}}}",
  nruns={{nruns}},
  nsums={{nsums}},
  kmap={{kmap}},
  solver=:petsc,
  petsc_options="{{{petsc_options}}}"
 )'

